risky: false

linting: true

preset: recommended

enabled:
  - long_array_syntax
  - no_spaces_after_function_name

disabled:
  - short_array_syntax
  - no_spaces_inside_parenthesis
  - no_spaces_inside_offset
  - no_tab_indentation
