sudo: false

language:
  - php

php:
  - 5.3
  - 5.6

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_script:
  - curl https://raw.githubusercontent.com/KamataRyo/travis-sctipts-collection/master/install-wp-tests.sh > ./install-wp-tests.sh
  - bash ./install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm cache clean
  - travis_retry npm install
  - npm run build

script:
- npm test
- phpunit

after_success:
- npm run generatePot
- curl https://raw.githubusercontent.com/KamataRyo/travis-sctipts-collection/master/deploy-wp-plugin.sh | bash

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  global:
  - WP_VERSION_TO_DEPLOY: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - WP_MULTISITE_TO_DEPLOY: 0
  - SVN_REF: https://plugins.svn.wordpress.org/oembed-travis/
  - GH_REF: github.com/KamataRyo/oembed-travis.git
  - secure: "a/QQ7WgztQeINOonHMRMwsczbjhmSsjkPpcZA85QvbCnj2An+uiGGijeukufcvmeeyszE0o7sYBjiWv8ll1jiOf0W+ETcP5Go4HAK5osUGpHIrDnYjitW2UPXtd6SONL5e9HHFi5aSFNNdLrU2Ohl2r45e7TP6J159rausEysmsBY+5OjnqazHunDbl+qszSAoI3oQC3Z0Yi1fWbvmK5rkhCslq/2LOdJkkHmOnDYnGH+NGiX04koUnK5EzT2i4tTiNjNboH51khwXhcIB0TL3FwNjRFmOvUv7B3sbDciiJrdSnmFtlBPqR7LLI3180kLr1A6LRzM5HmGFTAmb4kKH8bRyIox5Q7/svD7b6/IYq8gyVULhSKacAYtku2LZSC3KOFp0RU9hAgPmZ+YGMlq1B7ONoD16U0CXyfF/PJQkYX/GoPLUK6vM1mdv155SJVJOPjtQGgOwRtCjZJeGNYqi9Fu5GIoYU1LFx1UvV1SK/PrkpoSOLARba5MG2EhoZzQHq0lhCImlyvCCH1s2I6dFGiDhvqzWEFvZGacoy+IgndtMmNSU0JlNo8cjIApJDbzGXWyLI9vjC1GcF+TQjMQrJhEvqdTzdLlX+C5Ro1KoZynA74S1I1L0bnpD9uWnPXk6akAnqa1QjMKzhpJnaRLIXaJRB8We+9mr5pYpFur6U="
