sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v?[0-9](\.[0-9])*/

php:
  - 5.3
  - 5.6

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm cache clean
  - npm install -g  npm-install-retry
  - npm-install-retry --wait 500 --attempts 10
  - gem install compass

script:
  - npm test
  - phpunit

after_success:
  - npm run generatePot
  - bash bin/deploy.sh

env:
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0

  global:
    - WP_VERSION_TO_DEPLOY: latest
    - PHP_VERSION_TO_DEPLOY: 5.6
    - WP_MULTISITE_TO_DEPLOY: 0
    - GH_REF: github.com/KamataRyo/inherit-theme-mods.git

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
