sudo: false

language:
  - php

php:
  - 5.3
  - 5.6

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- npm cache clean
- travis_retry npm install
- npm run build

script:
- npm test
- phpunit

after_success:
- npm run generatePot
- bash bin/deploy.sh

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  global:
  - WP_VERSION_TO_DEPLOY: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - WP_MULTISITE_TO_DEPLOY: 0
  - GH_REF: github.com/KamataRyo/oembed-travis.git
  - secure: "KCj0W0fXUbf7CtJE5r9Yibn5sdQ3tzOvDKxdOXTvgTNjRyfFhtpHjzxyw/DNa7RE3VlnXp464k1oZHvnVeI1ly3dRHGHsmeAWBqX1VoT/5irGTgjA2B2Qqa3IGop5XJGYlRAadYGZuRLRv13f6/eJ3D+k/++EcaQLXxj+1VnViaNlUUBWnpGglyD53BdDbu0x2vqnnRpXIpay/wXFxsDdIUCAL8njqRQsDdei0xfdSUtdG/fzXFXqLpJ5U5sgSto350dSe9AuT19vt1t8+y5BYrLt6ATYy5jy+SbaP8qkkgQ4d1yDVvgGoDbUI/PoDAEuYGqX8HJPJP917wo8SxYGKqP1ijAHg6pKOHcWPmtxTUB8ewtGbDX6GymUG4TosdXLKeVhN0Ijz4+4v3it9EP7/ps4B2k/fNPnDBn+73EA2eE4FBWqICnMv0gZ/EtDC591xKM/HC1sm9oS+B+QzRIYtSWBbLXp5wEgCvKsIbrXG6tsZOVDTJubg5zICfqjVSOBhp31vXS4p8+zubkBpR9ED7PmwgQEDN5XYoLTyW+CTSMfypetvt1xtuDuhj7uE4nwCbwwonqEfp1zmc96i7u2M1G3U5DAniZ10tcxxD8bvXV7vxgH7eEA1Wgej5yoN30wO2xtUIibP6/ndWcZIDD7hq344ZFz/NeiF4ULmKPANg="

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1
