sudo: false

language:
  - php

php:
  - 5.3
  - 5.6

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- npm cache clean
- travis_retry npm install
- npm run build

script:
- npm test
- phpunit

after_success:
- npm run generatePot
- bash bin/deploy.sh

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  global:
  - WP_VERSION_TO_DEPLOY: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - WP_MULTISITE_TO_DEPLOY: 0
  - SVN_REPO: https://plugins.svn.wordpress.org/oembed-travis/
  - GH_REF: github.com/KamataRyo/oembed-travis.git
  - secure: "bggJQt5NRDdSvcGNZiGNb5lLw145XaMykoAu5RsTppcff8kVZMqvv+hJugNpRfugPSsPynRcl4IyilvFUjYVCUDEeNxSksiuUDZUCePaB81gGr1L8GcGj8853O5Kh90AMcuC+3Muy+1pQtcDV1QXsVQlSsJ6F8V4uR1LmQJ5GUKmcBeQWDoadXq/bt0xdVW1G2LPUniHlzA8ukYmrS0RLZ0o57WB0YwBoJ140YIpATimOJE3StTF3AHCPgG8goZ+Qf0XSU9pxhfrfa7R+DlpWOh+2M5FK6RV96WUjNoVXTptnaw7JdXeNRU8dAmKW6NwgFayksaYSQMBOPaFC7rgnTlzNtc6MpiR4NEaUkcjRb+nyIvZXF8z/tGNIzD78MkJRnVqA+DGmiXyYMUBnfcjqwk7KqcIfra6ygelKPJl6eBPUvGwl8vWZjsew7kHHHZ6FQ7lXJqzVMbvFhcYa8KPX7AzqeHmcZjFlf5x/xxziVMD1aO5bln4Q4V5UURv6S/8b7ytsLxRCExLq9677YdF+/+/duhPj5YiSFaA9LXodAYY8xwL+Y+3ewPUC6e7/hOjx9WZ0rVjfQMo5SGaZX8ikXSTppTEbaA+OuUqmOzysvq/1Qi08vIJ6sSRPi8MnqNkB4sl6wmElqyKJHkj4W+5l4u7bvNE3R226RfOuD86j40="
