sudo: false

language:
  - php

php:
  - 5.3
  - 5.6

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- npm cache clean
- travis_retry npm install
- npm run build

script:
- npm test
- phpunit

after_success:
- npm run generatePot
- bash bin/deploy.sh

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  global:
  - WP_VERSION_TO_DEPLOY: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - WP_MULTISITE_TO_DEPLOY: 0
  - SVN_REPO: https://plugins.svn.wordpress.org/oembed-travis/
  - GH_REF: https://github.com/KamataRyo/oembed-travis.git
  - secure: "UGZzO2yP5Qab/sYEVieNVKlizhLs066hRGY4Vc0bY5rcymnk2qTxqSngU7/ydQqE9H0StM0ou8umihGttJsDgsOlbw8PDBpABqQcRT8zR0yvreqOPaPZUzIPGCDLwbGBFVA/xgfr8bt4ivweROwLyGFU5G1iCoy/TKB0sifkalT8hP9Xp2ko8Ph5AtohT688vEJoWylkGREPKyN2k3rFP6LIESYS3DdxUVYMqW7G74p4gg54SHVnRN8X7M39nZwtl3JaOGfMAG5POdS7BqoIXvp+et+fAavj4+aIRo1XcC+yM9fR9EBFvme4/zIatYCWD+kHyu6MvTWq2vB/JNeUWV1hlrganUzxQRhd1u2P3jFJKnqFKOgir2zYGo9tzObPuOgSEa2a4VIuVEEYBrh92CjIFY8lK2Hi2KdSFWocfOJfTb2xaiVNaE2gC1BoHXud4x58EGFU0dgivA1NjXLMC1o8QSIOKdhbadgM2Ykj1z6cTOXSe7Vp1ocAC31EFGHlfWvhr+8Vj4kIE+bmIsjOmG5jdoNknSEWYKpXdu9ypIH1y4CwFhum5SRpC57/rUQCEmLz5NOlTJF1LBl8Tq4599U16HgVj7lEOL9rNs57wb4XGCAsSMNIcP2wVdxpH4dqjAYOJlNQzYuVhpgykUEnCWGV8jUUQifq5LmlRIYyLgw="
