sudo: false

language:
  - php

php:
  - 5.3
  - 5.6

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_script:
- wget https://gist.githubusercontent.com/KamataRyo/cf31b8ffe87cebae64a3acf702692e76/raw/7f9aac841b5c9be3de235b6c70c480fbdaa50c34/install-wp-tests.sh > ./install-wp-tests.sh
- bash install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- npm cache clean
- travis_retry npm install
- npm run build

script:
- npm test
- phpunit

after_success:
- npm run generatePot
- curl https://gist.githubusercontent.com/KamataRyo/8fd5e7b6aea4de1b3b48a5f4c429ecbe/raw/df91683e27a18e62e441fae6e0bc95b4d49d67b0/wp_plugin_deploy.sh | bash

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest WP_MULTISITE=1

env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0
  global:
  - WP_VERSION_TO_DEPLOY: latest
  - PHP_VERSION_TO_DEPLOY: 5.6
  - WP_MULTISITE_TO_DEPLOY: 0
  - SVN_REPO: https://plugins.svn.wordpress.org/oembed-travis/
  - GH_REF: github.com/KamataRyo/oembed-travis.git
  - secure: "RS7bvoAgoox679R5c/yuXDPO7sriUeDX6fOH8I7WM4D8t5Gv/+d7mnrtScXSNo/PSBF1fPOwkhyrmwdsm7YfA75rwTVgeEavNxDgmKAdxMEkelXZKaQyjHoDe8ckrOUNAJ/KZ3stBQ0ibZRrrPDbFXvFrKHyOWUL7L3xEyQK4youylzuPY5eyvVHFckbvG2InomAWfx4D9CKEn7j/jzkH6WRerWDsnG1VAtuIHqnuDBzViRuOG6YduHeeBf3HaevMALtL+8aDVKZt+9thXuFf3g9MMy77iWFxTGEwWl5m1tz1s2iTY/XPZa7ETTxe1D+negP1HD2K6ZK6Co7xbd1twdVJtobrh1OjUA8y7sgWUuZz/rAyeBCyjpQ+HPEAwh6F5wm3vicXINSAM70E6wpnA/7Z4/rVghgUXngP/fjTbd2tcsdO70Zx22/kt8yBOxoHhk+MPZS+GV66ZR93EgmzXkWBFOXJ1BlSt9v+LhK++y0nwTQXnp85j63y5SbfgrdG09Y+qzjlG1Qlro2z/PAvQwVtrCaGbcx1N8gpZEguxey7FaTSpOy+dKOBymF6dt+G9EX8fDlM6FUncoB5sq5UAYQG1q5cDR/HKfNAcTIK4npiGROM1pcXpNVtqHX7rIN991DSGVje/qWEDm9Y1mRiGVtPXulrVOAsaQMylJJX0Q="
